# Generated by Django 5.2.1 on 2025-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Зал')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
