# Generated by Django 5.2.1 on 2025-05-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exhibits_alter_hall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibits',
            options={'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонаты'},
        ),
    ]
