# Generated by Django 5.2.1 on 2025-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exhibits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='square',
            field=models.FloatField(default=1, verbose_name='Площадь'),
            preserve_default=False,
        ),
    ]
