# Generated by Django 4.2.21 on 2025-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hall_level_hall_number_hall_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид искусства',
                'verbose_name_plural': 'Виды искусства',
            },
        ),
    ]
