# Generated by Django 4.2.21 on 2025-05-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artform'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibits',
            name='art_form',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artform'),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='period',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
    ]
