# Generated by Django 4.2.21 on 2025-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exhibits_art_form_alter_exhibits_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibits/'),
        ),
    ]
