# Generated by Django 4.2.21 on 2025-05-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_typeemployee_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
