# Generated by Django 4.2.21 on 2025-05-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_phone_number_employees_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibits',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees'),
        ),
    ]
