# Generated by Django 4.2.21 on 2025-05-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exhibits_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hall',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hall'),
        ),
    ]
