# Generated by Django 5.2.1 on 2025-05-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_exhibition_excursion_exposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees'),
        ),
    ]
