# Generated by Django 5.2.1 on 2025-05-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_excursion_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name': 'Экспозиция', 'verbose_name_plural': 'Экспозиции'},
        ),
    ]
