# Generated by Django 5.2.7 on 2025-11-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_phone', models.CharField(max_length=100, verbose_name='Рабочий телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Описание выполняемых работ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_contacts/')),
                ('employee', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
