# Generated by Django 5.2.7 on 2025-11-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_employeecontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontacts',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимый'),
        ),
    ]
