# Generated by Django 5.2.7 on 2025-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_employeecontacts_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('response_count', models.IntegerField(verbose_name='Количество откликов')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
