# Generated by Django 5.2.7 on 2025-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='response_count',
            field=models.IntegerField(default=0, verbose_name='Количество откликов'),
        ),
    ]
