# Generated by Django 5.2.7 on 2025-11-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_reviews_options_reviews_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('T', 'Active'), ('A', 'Archived'), ('D', 'Deleted')], default='T', max_length=1)),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Промокоды',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
