# Generated by Django 5.2.7 on 2025-11-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_order_purchasedexhibits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedexhibits',
            name='exhibit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exhibits'),
        ),
    ]
