# Generated by Django 5.2.7 on 2025-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_purchasedexhibits_exhibit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exhibits',
            field=models.ManyToManyField(to='main.purchasedexhibits'),
        ),
    ]
