# Generated by Django 5.2.7 on 2025-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_order_exhibits'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='discount',
            field=models.PositiveIntegerField(default=10, verbose_name='Скидка'),
            preserve_default=False,
        ),
    ]
